Set-ProcessMitigation -name firefox.exe -enable sehop
Set-ProcessMitigation -name firefox.exe -enable enableropsimexec
Set-ProcessMitigation -name firefox.exe -enable enableropcallercheck
Set-ProcessMitigation -name firefox.exe -enable enableropstackpivot
Set-ProcessMitigation -name firefox.exe -enable enableimportaddressfilter
Set-ProcessMitigation -name firefox.exe -enable BlockLowLabelImageLoads
Set-ProcessMitigation -name firefox.exe -enable PreferSystem32
Set-ProcessMitigation -name firefox.exe -enable BlockRemoteImageLoads
Set-ProcessMitigation -name firefox.exe -enable DisableNonSystemFonts
Set-ProcessMitigation -name firefox.exe -enable EnforceModuleDependencySigning
Set-ProcessMitigation -name firefox.exe -enable StrictCFG
Set-ProcessMitigation -name firefox.exe -enable SuppressExports
Set-ProcessMitigation -name firefox.exe -enable CFG
Set-ProcessMitigation -name firefox.exe -enable AllowThreadsToOptOut
Set-ProcessMitigation -name firefox.exe -enable DisableExtensionPoints
Set-ProcessMitigation -name firefox.exe -enable StrictHandle
Set-ProcessMitigation -name firefox.exe -enable HighEntropy
Set-ProcessMitigation -name firefox.exe -enable BottomUp
Set-ProcessMitigation -name firefox.exe -enable RequireInfo
Set-ProcessMitigation -name firefox.exe -enable ForceRelocateImages
Set-ProcessMitigation -name firefox.exe -enable EmulateAtlThunks
Set-ProcessMitigation -name firefox.exe -enable DEP
